### ISSUE TITLE
2 links created by one opk

### ISSUE THREAD

**Issue by geniot** [plrguez/fuse-od#1]
GMenu2x creates 2 links for fuse-1.5.7-od-v0.0.6.opk: regular and system versions. I guess it's a feature, but can you recommend how to leave only one link.

**Comment by plrguez** [comment]
Yes, it is a feature.

OPK are squashfs files. On linux you can use unsquashfs and mksquashfs commands to extract and compress OPK files:

For example to extract fuse-1.5.7-od-v0.0.6.opk to fuse directory use the command:
`unsquashfs -d fuse fuse-1.5.7-od-v0.0.6.opk`

Then you can make your changes, for example remove the `system.gcw0.desktop` file in the fuse directory to leave only the link for open with the file selector. desktop files are the links that GMenu2x show.

And compress again to a new opk file with a command like:
`mksquashfs ./fuse/* fuse-1.5.7-od-selector-v0.0.6.opk -all-root -noappend -no-exports -no-xattrs`

On windows machines I believe that 7zip have support squashfs but I don't have tested myself.

I've created an OPK file with only the link to the file selector. It's for 2014 OpenDingux based firmwares and I believe that is what you want. Inside the zip is the OPK file [fuse-1.5.7-od-selector-v0.0.6.zip](https://github.com/plrguez/fuse-od/files/6172530/fuse-1.5.7-od-selector-v0.0.6.zip)

I hope this have helped you.

**Comment by geniot** [comment]
Yes, it works like a charm. Thank you very much. 
I looked inside of the *.desktop files that work like icons. So, to tell GMenu2x that the launcher needs to start with a file selector we need to use %f at the end of Exec?
Exec=fuse-gcw0 %f
Or is it some other setting that I missed.

**Comment by plrguez** [comment]
Yes, the %f token is to indicate that the program need a file to load so the file selector is shown.

For some details about opk files and desktop meta-data files see https://github.com/retrogamehandheld/OpenDingux/wiki/How-to-make-an-OPK
