### ISSUE TITLE
Poke in Poke memory cannot be selected

### ISSUE THREAD

**Issue by geniot** [plrguez/fuse-od#2]
In Machine->Poke Memory an entry cannot be selected because X button triggers Add dialog. And X also is used to select a checkbox. 
I have Pocketgo2v2, latest version of Fuse - 0.0.6
I have tried to set Pokes in Fuse on Windows. Same .z80 file. It works. 
On PocketGo I have tried to set Pokes manually and loading a .pok file. The list of pokes is loaded but checkboxes cannot be selected because X is used to add pokes (this is my guess why it is not working).

**Comment by plrguez** [comment]
You are right, this is a bug. I'll fix it for the next release.

This is a work in progress build for 2014 OpenDingux with the fix and upgraded to Fuse 1.6.0  [fuse-1.6.0-od-selector-v0.0.7-wip.zip] (https://github.com/plrguez/fuse-od/files/6176380/fuse-1.6.0-od-selector-v0.0.7-wip.zip). Now the Y button is used to Add pokes and the X button to select pokes.

Thank you for reporting

**Comment by geniot** [comment]
Thank you very much for the fix and the new opk. I have just tested it. 
Everything works as expected: poking memory, pokes from file. 
One small thing I noticed though: after loading pokes from a file, control mapping stops to work. So I have to load Joysticks>Load control mapping from file again after loading pokes. Somehow loading pokes from a file resets / disables control mapping.

**Comment by plrguez** [comment]
I've see it. Fixed! 

Test this version [fuse-1.6.0-od-selector-v0.0.7-wip.zip](https://github.com/plrguez/fuse-od/files/6178303/fuse-1.6.0-od-selector-v0.0.7-wip.zip)

**Comment by geniot** [comment]
Yes, it works now. Thanks!

**Comment by plrguez** [comment]
Fixed in [release v0.0.7](https://github.com/plrguez/fuse-od/releases/tag/v0.0.7)
