### ISSUE TITLE
Fuse fails to pick up tape load from loaded state

### ISSUE THREAD

**Issue by geniot** [plrguez/fuse-od#5]
How to reproduce:
1. Load the tzx file.
2. Save state when in game menu.
3. Exit Fuse.
4. Open tzx again.
5. Load state. 
6. Choose start game (space). 

The loaded snapshot fails to pick up tape loading. I tried Media>Tape>Open/Play even Browse. Nothing works. The loaded state is stuck. Game does not start. You can try to start the game from the tzx load. It works. 
Also tape loading / pick up does not work when finishing Level 1 of the game and trying to load Level 2. That's where I actually faced this problem. 
Thanks.

[Myth.tzx.zip](https://github.com/plrguez/fuse-od/files/6218029/Myth.tzx.zip)

**Comment by geniot** [comment]
I found a different tape file that actually works in this scenario. So I guess we can close the issue. Solution: look for a better tape. Could it be that the extension matters?  I have no idea what the difference is between tzx and tap but tap turned out to be working.

**Comment by geniot** [comment]
After some testing it looks like this bug depends on the point where save is made and on the tape file.
Update: 
after even some more testing I take my statement back. Fuse on PocketGo2v2 cannot pick up the game from the saved state if the game file is loaded from tape in steps (levels/stages).

**Comment by geniot** [comment]
The solution (finally I found it!) is to use an SCL file.

.SCL - another popular TR-DOS format which is more compact and may contain a greater number of files. Likewise, can only be run in either Pentagon 128 or Scorpion 256 mode.

So to run an SCL file on Fuse you would need Scorpion 256 rom. Which is not included. But since I can build my OPK from the source code I can download it and include it. 

It turns out that Fuse is capable to pick up the game level load from an SCL file but not from a TAP file (I tested only with "Myth - History in the Making").

Also I'm going to release my custom Fuse opk in my fork. It will contain the missing rom files and some other minor changes (1 link instead of 2 and no version number in the name of the link).

**Comment by plrguez** [comment]
Hello geniot,

You can add additional roms in the $HOME/.fuse/roms directory. No roms other than those included with upstream Fuse will be included in my port. The main reason is that there are no rights to distribute them freely.

The savestates functionality does not save any information about the inserted media, for example, the position of the tape. It is just a numbered snapshot saved in folders named as a loaded program. So for tapes, you need to use the tape browser to load the tape after loading any save state and moving forward through the game.

Real life do not leave me enough free time to move forward a lot here right now. I should soon release the latest fixes I made and the upgrade to Fuse version 1.6.0, but right now I don't have time. But feel free in your fork to move forward and include what you consider necessary, it is the ease that open source and these tools give us ;) I will try to take a look from time to time.
