### ISSUE TITLE
how it works..

### ISSUE THREAD

**Issue by ahahahaah** [plrguez/fuse-od#6]
hello,
i wanted to test fuse in the retrofw firmware
so i launched the game "abu simbel profanation".
ok now i have a menu that says "2 kempston  3 keyboard  4 instructions"
so i diplayed the virtual keyboard and hit the 2 or 3 or 4 and nothing happened
so after some inactiviy seconds the demo mode of th game runs , during the demo when i use the virtual keyboard to press the sp key, the choice menu displays again (so the virtual keyboard works) but again i press 2 and 3 and 4 keys of the virtual keyboard but nothing happens

do you know what is the problem. can you help please?

**Comment by geniot** [comment]
Does it fail like this in other games too? I mean: is it really a Fuse emulator problem or maybe a game rom problem?
I agree it's strange that SPACE works and numbers don't. It's not consistent. 
You can also try to map 1-2-3 to A-B-X buttons to test whether numbers will work with button assignment.

**Comment by ahahahaah** [comment]
not in the other games i've just tested, so maybe it's the game rom :'(
so it's ok for this

and i wanted to ask if the loading sound exists for all games or not? because the option is activated but when i load games there is no loading sound.

**Comment by plrguez** [comment]
Hi,

For Abu Simbel Profanation you need to use the 48K model and enable "Issue 2 keyboard", at least with the original releases. To do this press the Select button to open the menu, select Options menu and then select General... This opens the General options form. Go to "Issue 2 keyboard", the third option, and pressing the X button you will enable it (or disable it if previously are enabled), and accept general options form pressing the A button.

Yes, the loading sound exist :) You must deactivate the "Fastloading", "Use tape traps" and "Accelerate loaders" options in the Media menu and enable the "Loading sound" option in Sound menu.

Remember, the X button is to enable/disable the check options and the A button is to accept the changes, if you exit with B button the changes will be lost.

**Comment by ahahahaah** [comment]
omg!! thank you dude, u are incredible lol
all works now. i'd never find all these tricks by myself lol
thanks
