### ISSUE TITLE
Opendingux Beta Lepus Support

### ISSUE THREAD

**Issue by tmznix** [plrguez/fuse-od#7]
Hi, if possible, please add Lepus devices support.

Thank you in advance :)

Cheers!

**Comment by plrguez** [comment]
Hi,

Yes, it is planned a Lepus build. I have to bump builds to Fuse version 1.6.0 and then I will include Lepus build. 

I hope I release it during this month.

The next version will include few changes:
- The current 1.5.7 builds have almost all the changes from upstream 1.6.0, so it will be just a simple label change.
- A bug fix for the Poke memory widget to allow enable / disable pokes
- A bug fix to avoid loading a control mapping file when loading a .pok file

**Comment by plrguez** [comment]
OD beta lepus build released. Downloads [here](https://github.com/plrguez/fuse-od/releases/tag/v0.0.7)
